#!/usr/bin/env python3
"""
Train XGBoost on synthetic behavioral data for pure Python inference.
Outputs `api/model_logic.py` via `m2cgen`.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import m2cgen as m2c
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

HERE = Path(__file__).resolve().parent
MODEL_PYTHON_LOGIC = HERE / "api" / "model_logic.py"

FEATURES = [
    "AGE",
    "EXT_SOURCE_1",
    "UPI_VELOCITY",
    "BILL_PAY_CONSISTENCY",
    "APP_USAGE_DAYS",
]


def generate_synthetic_data(n_samples: int = 10000) -> pd.DataFrame:
    """Generate fake data to mimic credit scoring behavior."""
    rng = np.random.default_rng(42)
    
    age = rng.uniform(20, 70, n_samples)
    ext_1 = rng.uniform(0, 1, n_samples)
    upi = rng.uniform(0, 1, n_samples)
    bill = rng.uniform(0, 1, n_samples)
    app = rng.uniform(0, 300, n_samples)
    
    # Risk weights — MUST sum to 1.0
    # BILL_PAY_CONSISTENCY is the strongest driver (35%).
    # APP_USAGE_DAYS now has meaningful pull (15%).
    # EXT_SOURCE_1 (CIBIL) still important but not dominant (30%).
    # UPI_VELOCITY moderate (15%). AGE minimal (5%).
    risk = (
        (70 - age) / 50 * 0.05 +       # AGE:                  5%
        (1 - ext_1) * 0.30 +            # EXT_SOURCE_1 (CIBIL): 30%
        (1 - upi) * 0.15 +              # UPI_VELOCITY:         15%
        (1 - bill) * 0.35 +             # BILL_PAY_CONSISTENCY: 35%  ← primary driver
        (1 - app/300) * 0.15            # APP_USAGE_DAYS:       15%
    )
    
    # 10% base noise
    risk += rng.normal(0, 0.1, n_samples)
    
    # 1 if risk > 0.65 threshold (defaulted), else 0
    target = (risk > 0.65).astype(int)
    
    return pd.DataFrame({
        "AGE": age,
        "EXT_SOURCE_1": ext_1,
        "UPI_VELOCITY": upi,
        "BILL_PAY_CONSISTENCY": bill,
        "APP_USAGE_DAYS": app,
        "TARGET": target
    })


def main() -> None:
    print("Generating synthetic credit behavioral data...")
    df = generate_synthetic_data(10000)
    X = df[FEATURES]
    y = df["TARGET"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    neg = (y_train == 0).sum()
    pos = (y_train == 1).sum()
    scale_pos_weight = float(neg / pos) if pos else 1.0

    model = XGBClassifier(
        n_estimators=100,
        max_depth=5,
        learning_rate=0.1,
        scale_pos_weight=scale_pos_weight,
        base_score=0.5,
        random_state=42,
        eval_metric="logloss",
        n_jobs=-1,
    )

    print("Training the CreditNeverBefore Engine (Synthetic)...")
    print(f"scale_pos_weight: {scale_pos_weight:.4f}")
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    proba = model.predict_proba(X_test)[:, 1]
    auc = roc_auc_score(y_test, proba)
    print(f"\nModel Performance (AUC-ROC): {auc:.4f}")
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    print("\nExporting model to pure Python logic via m2cgen...")
    python_code = m2c.export_to_python(model)
    with open(MODEL_PYTHON_LOGIC, "w") as f:
        f.write("# Pure Python inference logic for CreditNeverBefore\n")
        f.write("# Generated by m2cgen; no dependencies required for prediction\n")
        f.write(python_code)
    print(f"Final model logic saved to: {MODEL_PYTHON_LOGIC}")


if __name__ == "__main__":
    main()
